apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: dbserver
  name: dbserver
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dbserver
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/k8-nodeapp-default: "true"
        io.kompose.service: dbserver
    spec:
      containers:
        - env:
            - name: MARIADB_DATABASE
              value: foodbase
            - name: MARIADB_HOME
              value: /var/lib/mysql
            - name: MARIADB_ROOT_PASSWORD
              value: "1234"
          image: jmguru/k8-nodeapp-dbserver:latest
          name: dbserver
          ports:
            - containerPort: 3306
              hostPort: 3306
              protocol: TCP
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred
